### ISSUE TITLE
locked out of main repo

### ISSUE THREAD

**Issue by ctaggart** [ctaggart/fsharp-companies#1]
@kavignon, any idea what is going on here?

![image](https://user-images.githubusercontent.com/80104/64260505-459d7080-cf2b-11e9-8dbd-ac7655dab4c2.png)

**Comment by Kavignon** [comment]
I'm so sorry! I was trying to find a way to deal with a mess that was occurring on the repository and seems that was a bad way. The situation has been fixed and you should be able to update the repository now. Sorry for the confusion! 
Hope to see a PR from you soon :)

**Comment by Kavignon** [comment]
@ctaggart Are you still locked out?

**Comment by ctaggart** [comment]
No
